#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/resscheduler
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/resscheduler
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = memquota.o resscheduler.o

include $(top_srcdir)/src/backend/common.mk
