#-------------------------------------------------------------------------
#
#    Makefile for utils/gp
#
# Copyright (c) Greenplum 2010
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/gp
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = segadmin.o persistentutil.o


include $(top_srcdir)/src/backend/common.mk
