#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/gpmon
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/utils/fmgr/Makefile,v 1.17 2004/05/21 20:56:49 tgl Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/gpmon
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = gpmon.o 


include $(top_srcdir)/src/backend/common.mk
