/*-------------------------------------------------------------------------
 *
 * pg_tidycat.h
 *	  
 * Copyright (c) 2011, 2012 Greenplum inc.
 *
 * WARNING: DO NOT MODIFY THIS FILE: 
 *  Generated by ./tidycat.pl version 34
 *  on Wed Feb  5 22:00:04 2014
 *-------------------------------------------------------------------------
 */


#include "catalog/pg_attribute_encoding.h"
#include "catalog/pg_auth_time_constraint.h"
#include "catalog/pg_compression.h"
#include "catalog/pg_filesystem.h"
#include "catalog/pg_foreign_data_wrapper.h"
#include "catalog/pg_foreign_server.h"
#include "catalog/pg_foreign_table.h"
#include "catalog/pg_partition_encoding.h"
#include "catalog/pg_proc_callback.h"
#include "catalog/pg_remote_credentials.h"
#include "catalog/pg_type_encoding.h"
