/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_sql_Types */

#ifndef _Included_java_sql_Types
#define _Included_java_sql_Types
#ifdef __cplusplus
extern "C" {
#endif
#undef java_sql_Types_BIT
#define java_sql_Types_BIT -7L
#undef java_sql_Types_TINYINT
#define java_sql_Types_TINYINT -6L
#undef java_sql_Types_SMALLINT
#define java_sql_Types_SMALLINT 5L
#undef java_sql_Types_INTEGER
#define java_sql_Types_INTEGER 4L
#undef java_sql_Types_BIGINT
#define java_sql_Types_BIGINT -5L
#undef java_sql_Types_FLOAT
#define java_sql_Types_FLOAT 6L
#undef java_sql_Types_REAL
#define java_sql_Types_REAL 7L
#undef java_sql_Types_DOUBLE
#define java_sql_Types_DOUBLE 8L
#undef java_sql_Types_NUMERIC
#define java_sql_Types_NUMERIC 2L
#undef java_sql_Types_DECIMAL
#define java_sql_Types_DECIMAL 3L
#undef java_sql_Types_CHAR
#define java_sql_Types_CHAR 1L
#undef java_sql_Types_VARCHAR
#define java_sql_Types_VARCHAR 12L
#undef java_sql_Types_LONGVARCHAR
#define java_sql_Types_LONGVARCHAR -1L
#undef java_sql_Types_DATE
#define java_sql_Types_DATE 91L
#undef java_sql_Types_TIME
#define java_sql_Types_TIME 92L
#undef java_sql_Types_TIMESTAMP
#define java_sql_Types_TIMESTAMP 93L
#undef java_sql_Types_BINARY
#define java_sql_Types_BINARY -2L
#undef java_sql_Types_VARBINARY
#define java_sql_Types_VARBINARY -3L
#undef java_sql_Types_LONGVARBINARY
#define java_sql_Types_LONGVARBINARY -4L
#undef java_sql_Types_NULL
#define java_sql_Types_NULL 0L
#undef java_sql_Types_OTHER
#define java_sql_Types_OTHER 1111L
#undef java_sql_Types_JAVA_OBJECT
#define java_sql_Types_JAVA_OBJECT 2000L
#undef java_sql_Types_DISTINCT
#define java_sql_Types_DISTINCT 2001L
#undef java_sql_Types_STRUCT
#define java_sql_Types_STRUCT 2002L
#undef java_sql_Types_ARRAY
#define java_sql_Types_ARRAY 2003L
#undef java_sql_Types_BLOB
#define java_sql_Types_BLOB 2004L
#undef java_sql_Types_CLOB
#define java_sql_Types_CLOB 2005L
#undef java_sql_Types_REF
#define java_sql_Types_REF 2006L
#undef java_sql_Types_DATALINK
#define java_sql_Types_DATALINK 70L
#undef java_sql_Types_BOOLEAN
#define java_sql_Types_BOOLEAN 16L
#ifdef __cplusplus
}
#endif
#endif
