#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/sort
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/utils/sort/Makefile,v 1.13 2003/11/29 19:52:04 pgsql Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/datumstream
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = datumstream.o datumstreamblock.o

include $(top_srcdir)/src/backend/common.mk