#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for catalog/hcatalog
#
#-------------------------------------------------------------------------

subdir = src/backend/catalog/hcatalog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = externalmd.o

include $(top_srcdir)/src/backend/common.mk

