#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for port/beos
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/port/beos/Makefile,v 1.4 2003/11/29 19:51:54 pgsql Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/port/beos
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = sem.o shm.o support.o

include $(top_srcdir)/src/backend/common.mk
