#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/resourcemanager/utils
#
#-------------------------------------------------------------------------

subdir = src/backend/resourcemanager/test
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global
OBJS = 
include $(top_srcdir)/src/backend/common.mk

