#!/bin/sh
#
# pxf-service	start/stop/initialize the PXF instance
#

source /etc/gphd/pxf/conf/pxf-env.sh

if [ ! -x $JAVA_HOME/bin/java ]; then
    echo \$JAVA_HOME is invalid
    exit 1
fi

pxf_user=pxf
pxf_root=/usr/lib/gphd/pxf

instance_root=/var/gphd/pxf
instance_name=pxf-service
instance_template=bio
instance_port=51200
instance_owner=pxf:hadoop

tcserver_root=/opt/vmware/vfabric-tc-server-standard

function createInstance()
{
	create_options="\
	--template $instance_template \
	--property ${instance_template}.http.port=$instance_port \
	--instance-directory $instance_root"

	mkdir -p $instance_root
	$tcserver_root/tcruntime-instance.sh create $create_options $instance_name

	if [ $? -gt 0 ]; then
		echo instance creation failed
		return 1
	fi

	chown $instance_owner -R $instance_root
}

function configureInstance()
{
	serverXml=$instance_root/$instance_name/conf/server.xml
	cat $serverXml | \
	sed "/^[[:blank:]]*maxKeepAliveRequests=.*$/ a\\
	maxHeaderCount=\"10000\"\\
	maxHttpHeaderSize=\"65536\"
	" > ${serverXml}.tmp

	rm $serverXml
	mv ${serverXml}.tmp $serverXml
}

function deployWebapp()
{
    cp $pxf_root/pxf.war $instance_root/$instance_name/webapps/
    cp $pxf_root/pxf-service-*[0-9].jar $instance_root/$instance_name/lib/
}

function checkWebapp()
{
	curl=`which curl`
	attempts=0
	max_attempts=300 # try to connect for 5 minutes
	sleep_time=1 # sleep 1 second between attempts
	
	# wait until tomcat is up:
	echo Waiting for tcServer to start...
	until [[ "`curl --silent --connect-timeout 1 -I http://localhost:${instance_port} | grep 'Coyote'`" != "" 
	   || "$attempts" -eq "$max_attempts" ]];
    do
        let attempts=attempts+1
        echo "tcServer not responding, re-trying after ${sleep_time} second (attempt number ${attempts})"
        sleep $sleep_time
    done
	if [[ "$attempts" -eq "$max_attempts" ]]; then
		echo ERROR: cannot connect to tcServer after 5 minutes
		return 1
	fi
	
	# check if PXF webapp is up:
	echo Checking if PXF webapp is up and running...
	curlResponse=$($curl -s "http://localhost:${instance_port}/pxf/v0")
	expectedResponse="Wrong version v0, supported version is v[0-9]+"
	
	if [[ $curlResponse =~ $expectedResponse ]]; then
		echo PXF webapp is up
		return 0
	fi
	
	echo ERROR: PXF webapp is inaccessible, check logs for more information
	return 1
}

function doInit()
{
	if [ -d $instance_root ]; then
		echo instance already exists in $instance_root, existing...
		return 1
	fi

	createInstance || return 1
	configureInstance || return 1
	deployWebapp || return 1
}

function doStartStop()
{
	command=$1
	pushd $instance_root
	runuser $pxf_user -c "$tcserver_root/tcruntime-ctl.sh $instance_name $command -n $instance_root -d $tcserver_root"
	if [ $? -ne 0 ]; then
		return 1
	fi 
	popd
	
	if [ "$command" = "start" ]; then
		checkWebapp || return 1
	fi
}

command=$1

case "$command" in
	"init" )
		doInit
		;;
	"start" )
		doStartStop $command
		;;
	"stop" )
		doStartStop $command
		;;
	"restart" )
		doStartStop stop
		sleep 1s
		doStartStop start
		;;
	* )
		echo $"Usage: $0 {start|stop|restart|init}"
		exit 2
		;;
esac

exit $?
