#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/appendonly
#
#-------------------------------------------------------------------------

subdir = src/backend/access/aocs
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = aocsam.o aocssegfiles.o

include $(top_srcdir)/src/backend/common.mk

