BIZHOME=/usr/local/bizgres
GPHOME=$BIZHOME/MPP_RELEASE_VERSION
PATH=$GPHOME/bin:$GPHOME/gpMgmt/bin:$PATH
DYLD_LIBRARY_PATH=$GPHOME/lib
MANPATH=$BIZHOME/doc:$MANPATH

export GPHOME
export BIZHOME
export PATH
export DYLD_LIBRARY_PATH
export MANPATH
