#ifndef RESOURCE_MANANGER_NULLABLE_BOOL_UTILITIES_H
#define RESOURCE_MANANGER_NULLABLE_BOOL_UTILITIES_H

enum NBOOL {
	BUNSET = -1,
	BFALSE = 0,
	BTRUE = 1
};

typedef enum NBOOL NBOOL;

#endif /* RESOURCE_MANANGER_NULLABLE_BOOL_UTILITIES_H */
