#
# Makefile for the access methods module
#
# $PostgreSQL: pgsql/src/backend/access/Makefile,v 1.14 2008/02/19 10:30:06 petere Exp $
#

subdir = src/backend/access/orc
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = orcsegfiles.o orcam.o

include $(top_srcdir)/src/backend/common.mk
