-- Dimension tables:
ALTER TABLE part ADD CONSTRAINT part_pkey PRIMARY KEY (P_PARTKEY);

ALTER TABLE region ADD CONSTRAINT region_pkey PRIMARY KEY (R_REGIONKEY);

ALTER TABLE nation ADD CONSTRAINT nation_pkey PRIMARY KEY (N_NATIONKEY);

ALTER TABLE SUPPLIER ADD CONSTRAINT supplier_pkey PRIMARY KEY (S_SUPPKEY);

ALTER TABLE CUSTOMER ADD CONSTRAINT customer_pkey PRIMARY KEY (C_CUSTKEY);

ALTER TABLE ORDERS ADD CONSTRAINT orders_pkey PRIMARY KEY (O_ORDERKEY);

-- ORDERS.CUSTKEY
	CREATE INDEX O_CUSTKEY_IX
	    ON orders (o_custkey);

-- LINEITEM.PARTKEY
	CREATE INDEX L_PARTKEY_IX
	    ON lineitem (l_partkey);

-- LINEITEM.QUANTITY
	CREATE INDEX L_QUANTITY_IX
	    ON lineitem (l_quantity);

-- LINEITEM.ORDERKEY
	CREATE INDEX L_ORDERKEY_IX
	    ON lineitem (l_orderkey);

-- LINEITEM.SUPPKEY
	CREATE INDEX L_SUPPKEY_IX
	    ON lineitem (l_suppkey);
