#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for port/qnx4
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/port/qnx4/Makefile,v 1.6 2003/11/29 19:51:54 pgsql Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/port/qnx4
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = isnan.o sem.o shm.o

include $(top_srcdir)/src/backend/common.mk
