CREATE ROLE super SUPERUSER;
SET SESSION AUTHORIZATION super;
CREATE ROLE u1;
CREATE DATABASE u1;
CREATE SCHEMA u1;
select nspname, rolname from pg_namespace n, pg_authid a where n.nspowner = a.oid and nspname = 'u1';
select datname, rolname from pg_database d, pg_authid a where d.datdba = a.oid and datname = 'u1';
alter database u1 owner to u1;
alter schema u1 owner to u1;
select nspname, rolname from pg_namespace n, pg_authid a where n.nspowner = a.oid and nspname = 'u1';
select datname, rolname from pg_database d, pg_authid a where d.datdba = a.oid and datname = 'u1';
RESET SESSION AUTHORIZATION;
DROP DATABASE u1;
DROP SCHEMA u1;
DROP ROLE u1;
DROP ROLE super;
