CREATE OR REPLACE FUNCTION sql_add(INTEGER, INTEGER)
RETURNS INTEGER
AS $$
    SELECT $1 + $2;
$$ LANGUAGE SQL;

SELECT sql_add(1, 2);

CREATE OR REPLACE FUNCTION sql_add_invalid(x INTEGER, y INTEGER)
RETURNS INTEGER
AS $$
    SELECT x + y;
$$ LANGUAGE SQL;
